import {
  Col,
  Row,
  Button,
  Modal,
  Form,
  Input,
  Space,
  Alert,
  notification,
  Grid,
} from 'antd'
import { useEffect, useState } from 'react'
import Head from 'next/head'
// import ForgotPassword from './forgotPassword'

import { signIn } from 'next-auth/react'
import Router from 'next/router'
import { LoginOutlined, ReloadOutlined } from '@ant-design/icons'
import { isMobile, isDesktop, isTablet } from '@/utils/screen'

const { useBreakpoint } = Grid

interface Props {
  without_layout: boolean
}

const Login = ({ without_layout }: Props) => {
  const [isModalOpen, setIsModalOpen] = useState(false)
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const screens = useBreakpoint()

  useEffect(() => {
    console.log('Mobile >> ', isMobile(screens))
    console.log('Tablet >> ', isTablet(screens))
    console.log('Desktop >> ', isDesktop(screens))
  })

  const onFinish = async (values: any) => {
    setError('')
    setLoading(true)

    const result = await signIn('credentials', {
      email: values.email,
      password: values.password,
      redirect: false,
      callbackUrl: '/',
    })

    setLoading(false)

    if (result?.error === 'CredentialsSignin') {
      setError('Email or Password is Wrong')
    } else {
      notification.success({
        message: 'Login Success',
      })

      if (result?.url) {
        Router.push(result?.url)
      }
    }
  }

  const onFinishFailed = (errorInfo: any) => {
    console.log('Failed:', errorInfo)
  }

  const handleOk = () => {
    setIsModalOpen(false)
  }

  const handleCancel = () => {
    setIsModalOpen(false)
  }

  return (
    <>
      <Head>
        <title>Login | Kapital Boost</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main data-page="login">
        <Row
          align={isMobile(screens) ? 'middle' : 'middle'}
          style={{ height: isMobile(screens) || screens.sm ? 'auto' : '100vh' }}
        >
          <Col sm={24} md={24} lg={14} xl={14} className="text-center">
            {isMobile(screens) || screens.sm ? (
              <img
                className="text-center"
                src={
                  'https://res.cloudinary.com/kbas/image/upload/v1562814565/logo/LOGO-17_djoes1.png'
                }
                alt="Illustration"
                width={'75%'}
                style={{
                  margin: 'auto',
                  marginBottom: '15px',
                  padding: '100px 0 10px',
                }}
              />
            ) : (
              <img
                className="illus hide-on-mobile"
                src={
                  'https://res.cloudinary.com/kbas/image/upload/v1677120908/Illustration/illustration_opbic0.svg'
                }
                alt="Illustration"
                width={'60%'}
                style={{
                  margin: 'auto',
                }}
              />
            )}
          </Col>

          <Col sm={24} md={24} lg={10} xl={10} className="login-form">
            <Space direction="vertical">
              <h1 className={`m-0 text-center-on-mobile`}>Sign In</h1>

              <p
                className={`m-0 text-center-on-mobile`}
                style={{ fontSize: '1.2rem' }}
              >{`Assalamu'alaikum KB's Team`}</p>

              <Form
                name="basic"
                style={{ marginTop: 25 }}
                initialValues={{ remember: true }}
                onFinish={onFinish}
                onFinishFailed={onFinishFailed}
                autoComplete="off"
                layout="vertical"
              >
                {error !== '' && <Alert message={error} type="error" />}
                <br />
                <Form.Item
                  label="Email"
                  name="email"
                  rules={[
                    { required: true, message: 'Please input your email!' },
                  ]}
                >
                  <Input size="large" />
                </Form.Item>

                <Form.Item
                  label="Password"
                  name="password"
                  rules={[
                    { required: true, message: 'Please input your password!' },
                  ]}
                >
                  <Input.Password size="large" />
                </Form.Item>

                {/* <Form.Item>
                  <Button
                    type="link"
                    onClick={() => setIsModalOpen(!isModalOpen)}
                    className="p-0"
                  >
                    Forgot password?
                  </Button>
                </Form.Item> */}

                <Form.Item>
                  <Space>
                    <Button
                      type="primary"
                      htmlType="submit"
                      loading={loading}
                      icon={<LoginOutlined />}
                      style={{ width: '175px' }}
                    >
                      Login
                    </Button>

                    <Button htmlType="reset" icon={<ReloadOutlined />}>
                      Reset
                    </Button>
                  </Space>
                </Form.Item>
              </Form>
            </Space>
          </Col>
        </Row>

        {/* <Modal
          title="Forgot Password"
          open={isModalOpen}
          onOk={handleOk}
          onCancel={handleCancel}
          footer={null}
        >
          <ForgotPassword handleClose={handleCancel} />
        </Modal> */}
      </main>
    </>
  )
}

export default Login

export const getServerSideProps = async () => {
  return {
    props: {
      without_layout: true,
    },
  }
}
