export const signersInitial = {
  investor: {
    type: 'investor',
    page: null,
    startX: 0,
    startY: 0,
    width: 240,
    height: 100,
    canvasWidth: 933,
    canvasHeight: 1324,
  },
  ukm_director: {
    type: 'ukm_director',
    page: null,
    startX: 0,
    startY: 0,
    width: 240,
    height: 100,
    canvasWidth: 933,
    canvasHeight: 1324,
  },
  ukm_commissioner: {
    type: 'ukm_commissioner',
    page: null,
    startX: 0,
    startY: 0,
    width: 240,
    height: 100,
    canvasWidth: 933,
    canvasHeight: 1324,
  },
  kb_director: {
    type: 'kb_director',
    page: null,
    startX: 0,
    startY: 0,
    width: 240,
    height: 100,
    canvasWidth: 933,
    canvasHeight: 1324,
  },
}
